### PR TITLE
Refactor method generation for greater clarity and consistency and enrich error messages

### PR DESCRIPTION
**Pull request by mulkieran**
Do a bunch of refactoring to simplify generation of invoker methods.

Enrich the DPClientGenerationError messages further.

Get rid of three pylint errors in the process.

Resolves: #7

### CODE REVIEW

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
It's probably a good sign that the only enhancement is further enriched DPClientGenerationError messages but that at the same time there is a net 15 line reduction.

**Comment by mulkieran** [comment]
I have every reason to believe that I ran our stratisd D-Bus tests using this version of the library and they passed.

**Comment by mulkieran** [comment]
Most of this is a refactoring, to flatten the methods out and have less nesting, which I think makes them a bit clearer. Anybody should probably feel comfortable with this. The other change is that DPClientGenerationErrors are made as informative as possible using a syntax which makes strings properly formatted when actually printed. Is there an objection to the messages or to the approach to formatting?

**Comment by agrover** [comment]
I'm not super familiar with this code but I am comfortable with this :smiley:  :+1:

**Comment by mulkieran** [comment]
This is blocking #12, so I'll just go ahead and merge.

**Pull request merged**
